FoodStore/Components/NavigationMenuViewComponent.cs
using FoodStore.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepo productRepo;

        public NavigationMenuViewComponent(IProductRepo productRepo)
        {
            this.productRepo = productRepo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(productRepo.Products.Select(p => p.Category)
                .Distinct()
                .OrderBy(c => c.CategoryName));
        }
    }
}

FoodStore/Views/Shared/ProductSummaryPartial.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.ProductName
            <span class="text-dark" style="float:right">
                <small>@Model.ProductPrice.ToString("c")</small>
            </span>
        </h4>
        @Model.ProductDescription
    </div>
    <form asp-page="/Cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <button type="submit" class="btn btn-dark text-white btn-sm" style="float:right">
            Add to cart
        </button>
    </form>
</div>
 

FoodStore/Views/Shared/ValidationPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("input.input-validation-error").addClass("is-invalid");
    });
</script>

FoodStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>FoodStore</title>
</head>
<body style="background-color: #eee;">

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2 text-center">TITLE</span>
        <form name="searchForm" asp-page="/Search" method="get" class="navbar-brand">
            <div class="d-flex flex-row align-items-center">
                <input id="SearchBar" type="search" name="productSearch" autocomplete="off" placeholder="Search" size="40" class="form-control" />
                <button type="submit" class="bg-info"><i class="fa fa-search"></i></button>
            </div>
            <div id="searchComplete" class="list-group position-absolute"></div>
        </form>    
    </div>
    <div class="row m-1 p-1">
        <div class="col-3">
            <vc:navigation-menu />
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script>

        $(function () {
            $("#SearchBar").keyup(function () {

                $.ajax({
                    type: "GET",
                    url: "/Search?handler=Searching",
                    data: { "prefix": $("#SearchBar").val() },
                    success: function (response) {

                        var list = document.createElement("li");

                        //remove's adding up to the list of prev search
                        if (document.getElementById("searchComplete").hasChildNodes())
                        {
                            document.getElementById("searchComplete").
                                removeChild(document.getElementById("searchComplete").firstChild);
                        }

                        let cnt = 0;
                        for (var i in response)
                        {
                            cnt++;
                            var btn = document.createElement("a");
                            var SearchRequest = new Request('/Search?productSearch='+response[i]);
                            btn.href = SearchRequest.url;
                            btn.setAttribute("class", "list-group-item bg-dark text-white");
                            btn.innerHTML = response[i];
                            btn.style.display = 'grid';
                            btn.style.textDecoration = 'none';
                            btn.style.fontSize = '15px';
                            btn.style.width = '350px';
                            btn.style.zIndex = '1';

                            //limts search succestion size to N => 5 items
                            if (cnt < 6) {
                                list.appendChild(btn);
                            }

                            console.log(btn);
                        }

                        document.getElementById("searchComplete").appendChild(list);
                        console.log(document.getElementById("searchComplete"));
                    },
                    failure: function (response) {
                        console.log("Fail", response);
                    },
                    error: function (response) {
                        console.log("Error", response);
                    }
                });
            });
        });

    </script>
</body>
</html>